services:
  nginx:
    restart: unless-stopped
    image: ${DOCKER_USERNAME}/money-tracker-frontend:latest
    ports:
      - 8080:80
    env_file:
      - ./frontend/.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

  backend:
    restart: unless-stopped
    image: ${DOCKER_USERNAME}/money-tracker-backend:latest
    ports:
      - 5001:5001
    env_file:
      - ./backend/.env
