###################################################
###### For Lets Encrypt SSL certificate ###########
###################################################

services:
  nginx:
    restart: unless-stopped
    image: ${DOCKER_USERNAME}/money-tracker-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    restart: unless-stopped
    image: ${DOCKER_USERNAME}/money-tracker-backend:latest
    expose:
      - "5001" # Only accessible to other containers
    env_file:
      - ./backend/.env
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
# ####################################################
# ######## For using cloudfront & load balancer ######
# ####################################################
# services:
#   nginx:
#     restart: unless-stopped
#     image: ${DOCKER_USERNAME}/quiz-frontend:latest
#     ports:
#       - 80:80
#       - 443:443
#     env_file:
#       - ./frontend/.env
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

#     depends_on:
#       - backend

#   backend:
#     restart: unless-stopped
#     image: ${DOCKER_USERNAME}/quiz-backend:latest
#     ports:
#       - 5000:5000
#     env_file:
#       - ./backend/.env
# ####################################################
# ######## For local development without SSL ##########
# services:
#   nginx:
#     restart: unless-stopped
#     image: ${DOCKER_USERNAME}/money-tracker-frontend:latest
#     ports:
#       - 8080:80
#     env_file:
#       - ./frontend/.env
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

#     depends_on:
#       - backend

#   backend:
#     restart: unless-stopped
#     image: ${DOCKER_USERNAME}/money-tracker-backend:latest
#     ports:
#       - 5001:5001
#     env_file:
#       - ./backend/.env
