services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80
    env_file:
      - ./frontend/.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .frontend/src/aws-exports.js:/app/src/aws-exports.js
      
    depends_on:
      - backend

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 5001:5001
    env_file:
      - ./backend/.env
